---
title: "Hotspots of change -Neotropical carnivores"
---

## Assessing hotspots of geographic range changes for eight charismatic Neotropical carnivores using integrated species distribution models

*Florencia Grattarola, Diana Bowler & Petr Keil*

This repository includes the data, code, model and outputs for our pre-print on the use of integrated species distribution models (ISDMs) to study the change in the geograhic distribution range of eight charismatic Neotropical carnivores.

**Species**: jaguarundi (*Herpailurus yagouaroundi*), ocelot (*Leopardus pardalis*), margay (*Leopardus wiedii*), coati (*Nasua nasua*), crab-eating fox (*Cerdocyon thous*), maned wolf (*Chrysocyon brachyurus*), tayra (*Eira barbara*), and giant river otter (*Pteronura brasiliensis*).  

### Find here

  - [Data](/data): PA and PO data to run the model + spatial data  
  - [Code](/code): code for all data processing + IDM run in JAGS   
  - [Models](/model): model file in BUGS language  
  - [Docs](/docs): model definitions + diagnostics + outputs + figures 

